// CONSTANTES DO ROBO
#define Largura_Robo 6.80f
#define Raio_roda 3.0f
// PINOS DO LEITOR DE BATERIA
#define ALL_CELLS p16
#define SINGLE_CELL p17


//PULSOS POR REVOLUÇÃO DO TACOMETRO
#define PULSES_REVOLUTION 12

//PINOS DE INTERRUPÇÃO DOS ENCODERS
#define TACHPIN_LEFT_1 p7
#define TACHPIN_LEFT_2 p8
#define TACHPIN_RIGHT_1 p29
#define TACHPIN_RIGHT_2 p30

//PINOS DOS MOTORES
#define MOTOR_RIGHT_PIN_1 p26   //MOTOR A -> MOTOR DA ((((DIREITA))))
#define MOTOR_RIGHT_PIN_2 p25
#define MOTOR_LEFT_PIN_1 p24   //MOTOR B -> MOTOR DA ((((ESQUERDA))))
#define MOTOR_LEFT_PIN_2 p23

//PINOS I2C PARA O IMU
#define IMU_SDA_PIN p28
#define IMU_SCL_PIN p27

//SERIAL ESCOLHIDO PARA A COMUNICAÇÃO COM XBEE
#define SERIAL_NUMBER 1

//ESCOLHE O VALOR DO SERIAL E DA INTERRUPÇÃO DO SERIAL CORRESPONDENTE
#if SERIAL_NUMBER == 3
#define xSER_INT LPC_UART3
#define TXPIN p9
#define RXPIN p10
#else
#if SERIAL_NUMBER == 1
#define xSER_INT LPC_UART1
#define TXPIN p13
#define RXPIN p14
#else
#define xSER_INT LPC_UART2
#define TXPIN p28
#define RXPIN p27
#endif
#endif
#define G 9.81