set(EIGEN_FILES
${LIB_DIR}/Eigen/Cholesky
${LIB_DIR}/Eigen/CholmodSupport
${LIB_DIR}/Eigen/Core
${LIB_DIR}/Eigen/Dense
${LIB_DIR}/Eigen/Eigen
${LIB_DIR}/Eigen/Eigenvalues
${LIB_DIR}/Eigen/Geometry
${LIB_DIR}/Eigen/Householder
${LIB_DIR}/Eigen/IterativeLinearSolvers
${LIB_DIR}/Eigen/Jacobi
${LIB_DIR}/Eigen/KLUSupport
${LIB_DIR}/Eigen/LU
${LIB_DIR}/Eigen/MetisSupport
${LIB_DIR}/Eigen/OrderingMethods
${LIB_DIR}/Eigen/PardisoSupport
${LIB_DIR}/Eigen/PaStiXSupport
${LIB_DIR}/Eigen/QR
${LIB_DIR}/Eigen/QtAlignedMalloc
${LIB_DIR}/Eigen/Sparse
${LIB_DIR}/Eigen/SparseCholesky
${LIB_DIR}/Eigen/SparseCore
${LIB_DIR}/Eigen/SparseLU
${LIB_DIR}/Eigen/SparseQR
${LIB_DIR}/Eigen/SPQRSupport
${LIB_DIR}/Eigen/StdDeque
${LIB_DIR}/Eigen/StdList
${LIB_DIR}/Eigen/StdVector
${LIB_DIR}/Eigen/SuperLUSupport
${LIB_DIR}/Eigen/SVD
${LIB_DIR}/Eigen/UmfPackSupport
${LIB_DIR}/Eigen/src/SVD/JacobiSVD.h
${LIB_DIR}/Eigen/src/SVD/UpperBidiagonalization.h
${LIB_DIR}/Eigen/src/SVD/SVDBase.h
${LIB_DIR}/Eigen/src/SVD/BDCSVD.h
${LIB_DIR}/Eigen/src/SVD/JacobiSVD_LAPACKE.h
${LIB_DIR}/Eigen/src/Jacobi/Jacobi.h
${LIB_DIR}/Eigen/src/Eigenvalues/ComplexEigenSolver.h
${LIB_DIR}/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h
${LIB_DIR}/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h
${LIB_DIR}/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h
${LIB_DIR}/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h
${LIB_DIR}/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h
${LIB_DIR}/Eigen/src/Eigenvalues/HessenbergDecomposition.h
${LIB_DIR}/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h
${LIB_DIR}/Eigen/src/Eigenvalues/Tridiagonalization.h
${LIB_DIR}/Eigen/src/Eigenvalues/RealQZ.h
${LIB_DIR}/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h
${LIB_DIR}/Eigen/src/Eigenvalues/EigenSolver.h
${LIB_DIR}/Eigen/src/Eigenvalues/ComplexSchur.h
${LIB_DIR}/Eigen/src/Eigenvalues/RealSchur.h
${LIB_DIR}/Eigen/src/UmfPackSupport/UmfPackSupport.h
${LIB_DIR}/Eigen/src/QR/HouseholderQR.h
${LIB_DIR}/Eigen/src/QR/CompleteOrthogonalDecomposition.h
${LIB_DIR}/Eigen/src/QR/ColPivHouseholderQR.h
${LIB_DIR}/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h
${LIB_DIR}/Eigen/src/QR/FullPivHouseholderQR.h
${LIB_DIR}/Eigen/src/QR/HouseholderQR_LAPACKE.h
${LIB_DIR}/Eigen/src/misc/lapacke_mangling.h
${LIB_DIR}/Eigen/src/misc/RealSvd2x2.h
${LIB_DIR}/Eigen/src/misc/lapack.h
${LIB_DIR}/Eigen/src/misc/blas.h
${LIB_DIR}/Eigen/src/misc/Image.h
${LIB_DIR}/Eigen/src/misc/lapacke.h
${LIB_DIR}/Eigen/src/misc/Kernel.h
${LIB_DIR}/Eigen/src/LU/InverseImpl.h
${LIB_DIR}/Eigen/src/LU/arch/Inverse_SSE.h
${LIB_DIR}/Eigen/src/LU/FullPivLU.h
${LIB_DIR}/Eigen/src/LU/PartialPivLU_LAPACKE.h
${LIB_DIR}/Eigen/src/LU/PartialPivLU.h
${LIB_DIR}/Eigen/src/LU/Determinant.h
${LIB_DIR}/Eigen/src/SuperLUSupport/SuperLUSupport.h
${LIB_DIR}/Eigen/src/Geometry/AlignedBox.h
${LIB_DIR}/Eigen/src/Geometry/Rotation2D.h
${LIB_DIR}/Eigen/src/Geometry/ParametrizedLine.h
${LIB_DIR}/Eigen/src/Geometry/Homogeneous.h
${LIB_DIR}/Eigen/src/Geometry/Translation.h
${LIB_DIR}/Eigen/src/Geometry/OrthoMethods.h
${LIB_DIR}/Eigen/src/Geometry/EulerAngles.h
${LIB_DIR}/Eigen/src/Geometry/Quaternion.h
${LIB_DIR}/Eigen/src/Geometry/arch/Geometry_SSE.h
${LIB_DIR}/Eigen/src/Geometry/Umeyama.h
${LIB_DIR}/Eigen/src/Geometry/Scaling.h
${LIB_DIR}/Eigen/src/Geometry/Transform.h
${LIB_DIR}/Eigen/src/Geometry/RotationBase.h
${LIB_DIR}/Eigen/src/Geometry/AngleAxis.h
${LIB_DIR}/Eigen/src/Geometry/Hyperplane.h
${LIB_DIR}/Eigen/src/PardisoSupport/PardisoSupport.h
${LIB_DIR}/Eigen/src/SparseQR/SparseQR.h
${LIB_DIR}/Eigen/src/Core/Dot.h
${LIB_DIR}/Eigen/src/Core/Random.h
${LIB_DIR}/Eigen/src/Core/MapBase.h
${LIB_DIR}/Eigen/src/Core/Reverse.h
${LIB_DIR}/Eigen/src/Core/CommaInitializer.h
${LIB_DIR}/Eigen/src/Core/CwiseUnaryOp.h
${LIB_DIR}/Eigen/src/Core/BooleanRedux.h
${LIB_DIR}/Eigen/src/Core/NestByValue.h
${LIB_DIR}/Eigen/src/Core/NumTraits.h
${LIB_DIR}/Eigen/src/Core/ProductEvaluators.h
${LIB_DIR}/Eigen/src/Core/Select.h
${LIB_DIR}/Eigen/src/Core/VectorwiseOp.h
${LIB_DIR}/Eigen/src/Core/EigenBase.h
${LIB_DIR}/Eigen/src/Core/Map.h
${LIB_DIR}/Eigen/src/Core/ArithmeticSequence.h
${LIB_DIR}/Eigen/src/Core/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/ReturnByValue.h
${LIB_DIR}/Eigen/src/Core/Visitor.h
${LIB_DIR}/Eigen/src/Core/Block.h
${LIB_DIR}/Eigen/src/Core/ArrayWrapper.h
${LIB_DIR}/Eigen/src/Core/SelfAdjointView.h
${LIB_DIR}/Eigen/src/Core/Diagonal.h
${LIB_DIR}/Eigen/src/Core/IO.h
${LIB_DIR}/Eigen/src/Core/products/Parallelizer.h
${LIB_DIR}/Eigen/src/Core/products/SelfadjointProduct.h
${LIB_DIR}/Eigen/src/Core/products/TriangularMatrixMatrix.h
${LIB_DIR}/Eigen/src/Core/products/SelfadjointMatrixVector.h
${LIB_DIR}/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/GeneralMatrixVector.h
${LIB_DIR}/Eigen/src/Core/products/SelfadjointRank2Update.h
${LIB_DIR}/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/GeneralBlockPanelKernel.h
${LIB_DIR}/Eigen/src/Core/products/TriangularSolverMatrix.h
${LIB_DIR}/Eigen/src/Core/products/GeneralMatrixMatrix.h
${LIB_DIR}/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h
${LIB_DIR}/Eigen/src/Core/products/SelfadjointMatrixMatrix.h
${LIB_DIR}/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/TriangularSolverVector.h
${LIB_DIR}/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h
${LIB_DIR}/Eigen/src/Core/products/TriangularMatrixVector.h
${LIB_DIR}/Eigen/src/Core/Stride.h
${LIB_DIR}/Eigen/src/Core/ArrayBase.h
${LIB_DIR}/Eigen/src/Core/BandMatrix.h
${LIB_DIR}/Eigen/src/Core/CoreIterators.h
${LIB_DIR}/Eigen/src/Core/Assign.h
${LIB_DIR}/Eigen/src/Core/SolveTriangular.h
${LIB_DIR}/Eigen/src/Core/Redux.h
${LIB_DIR}/Eigen/src/Core/Transpose.h
${LIB_DIR}/Eigen/src/Core/DenseBase.h
${LIB_DIR}/Eigen/src/Core/GenericPacketMath.h
${LIB_DIR}/Eigen/src/Core/SelfCwiseBinaryOp.h
${LIB_DIR}/Eigen/src/Core/Inverse.h
${LIB_DIR}/Eigen/src/Core/GlobalFunctions.h
${LIB_DIR}/Eigen/src/Core/Product.h
${LIB_DIR}/Eigen/src/Core/PermutationMatrix.h
${LIB_DIR}/Eigen/src/Core/ConditionEstimator.h
${LIB_DIR}/Eigen/src/Core/StableNorm.h
${LIB_DIR}/Eigen/src/Core/NoAlias.h
${LIB_DIR}/Eigen/src/Core/Fuzzy.h
${LIB_DIR}/Eigen/src/Core/SolverBase.h
${LIB_DIR}/Eigen/src/Core/ForceAlignedAccess.h
${LIB_DIR}/Eigen/src/Core/Solve.h
${LIB_DIR}/Eigen/src/Core/DenseCoeffsBase.h
${LIB_DIR}/Eigen/src/Core/CoreEvaluators.h
${LIB_DIR}/Eigen/src/Core/Array.h
${LIB_DIR}/Eigen/src/Core/arch/AVX512/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/AVX512/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/AVX/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/AVX/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/AVX/Complex.h
${LIB_DIR}/Eigen/src/Core/arch/AVX/TypeCasting.h
${LIB_DIR}/Eigen/src/Core/arch/NEON/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/NEON/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/NEON/Complex.h
${LIB_DIR}/Eigen/src/Core/arch/CUDA/Half.h
${LIB_DIR}/Eigen/src/Core/arch/CUDA/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/CUDA/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/CUDA/PacketMathHalf.h
${LIB_DIR}/Eigen/src/Core/arch/CUDA/Complex.h
${LIB_DIR}/Eigen/src/Core/arch/CUDA/TypeCasting.h
${LIB_DIR}/Eigen/src/Core/arch/Default/Settings.h
${LIB_DIR}/Eigen/src/Core/arch/Default/ConjHelper.h
${LIB_DIR}/Eigen/src/Core/arch/AltiVec/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/AltiVec/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/AltiVec/Complex.h
${LIB_DIR}/Eigen/src/Core/arch/ZVector/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/ZVector/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/ZVector/Complex.h
${LIB_DIR}/Eigen/src/Core/arch/SSE/MathFunctions.h
${LIB_DIR}/Eigen/src/Core/arch/SSE/PacketMath.h
${LIB_DIR}/Eigen/src/Core/arch/SSE/Complex.h
${LIB_DIR}/Eigen/src/Core/arch/SSE/TypeCasting.h
${LIB_DIR}/Eigen/src/Core/util/Memory.h
${LIB_DIR}/Eigen/src/Core/util/Constants.h
${LIB_DIR}/Eigen/src/Core/util/Macros.h
${LIB_DIR}/Eigen/src/Core/util/MKL_support.h
${LIB_DIR}/Eigen/src/Core/util/XprHelper.h
${LIB_DIR}/Eigen/src/Core/util/StaticAssert.h
${LIB_DIR}/Eigen/src/Core/util/BlasUtil.h
${LIB_DIR}/Eigen/src/Core/util/ForwardDeclarations.h
${LIB_DIR}/Eigen/src/Core/util/NonMPL2.h
${LIB_DIR}/Eigen/src/Core/util/SymbolicIndex.h
${LIB_DIR}/Eigen/src/Core/util/IntegralConstant.h
${LIB_DIR}/Eigen/src/Core/util/DisableStupidWarnings.h
${LIB_DIR}/Eigen/src/Core/util/ReenableStupidWarnings.h
${LIB_DIR}/Eigen/src/Core/util/IndexedViewHelper.h
${LIB_DIR}/Eigen/src/Core/util/Meta.h
${LIB_DIR}/Eigen/src/Core/CwiseUnaryView.h
${LIB_DIR}/Eigen/src/Core/IndexedView.h
${LIB_DIR}/Eigen/src/Core/TriangularMatrix.h
${LIB_DIR}/Eigen/src/Core/VectorBlock.h
${LIB_DIR}/Eigen/src/Core/AssignEvaluator.h
${LIB_DIR}/Eigen/src/Core/CwiseTernaryOp.h
${LIB_DIR}/Eigen/src/Core/MatrixBase.h
${LIB_DIR}/Eigen/src/Core/GeneralProduct.h
${LIB_DIR}/Eigen/src/Core/CwiseBinaryOp.h
${LIB_DIR}/Eigen/src/Core/Ref.h
${LIB_DIR}/Eigen/src/Core/Swap.h
${LIB_DIR}/Eigen/src/Core/Transpositions.h
${LIB_DIR}/Eigen/src/Core/Replicate.h
${LIB_DIR}/Eigen/src/Core/DenseStorage.h
${LIB_DIR}/Eigen/src/Core/Matrix.h
${LIB_DIR}/Eigen/src/Core/Assign_MKL.h
${LIB_DIR}/Eigen/src/Core/PlainObjectBase.h
${LIB_DIR}/Eigen/src/Core/DiagonalMatrix.h
${LIB_DIR}/Eigen/src/Core/DiagonalProduct.h
${LIB_DIR}/Eigen/src/Core/CwiseNullaryOp.h
${LIB_DIR}/Eigen/src/Core/MathFunctionsImpl.h
${LIB_DIR}/Eigen/src/Core/functors/AssignmentFunctors.h
${LIB_DIR}/Eigen/src/Core/functors/TernaryFunctors.h
${LIB_DIR}/Eigen/src/Core/functors/StlFunctors.h
${LIB_DIR}/Eigen/src/Core/functors/BinaryFunctors.h
${LIB_DIR}/Eigen/src/Core/functors/NullaryFunctors.h
${LIB_DIR}/Eigen/src/Core/functors/UnaryFunctors.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_kernel_bmod.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_column_dfs.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_panel_bmod.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_gemm_kernel.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_panel_dfs.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_relax_snode.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_pruneL.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_Utils.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_column_bmod.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_Structs.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLUImpl.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_pivotL.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h
${LIB_DIR}/Eigen/src/SparseLU/SparseLU_Memory.h
${LIB_DIR}/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h
${LIB_DIR}/Eigen/src/StlSupport/StdVector.h
${LIB_DIR}/Eigen/src/StlSupport/details.h
${LIB_DIR}/Eigen/src/StlSupport/StdList.h
${LIB_DIR}/Eigen/src/StlSupport/StdDeque.h
${LIB_DIR}/Eigen/src/MetisSupport/MetisSupport.h
${LIB_DIR}/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h
${LIB_DIR}/Eigen/src/SparseCholesky/SimplicialCholesky.h
${LIB_DIR}/Eigen/src/SparseCore/SparseCompressedBase.h
${LIB_DIR}/Eigen/src/SparseCore/SparseCwiseUnaryOp.h
${LIB_DIR}/Eigen/src/SparseCore/SparseVector.h
${LIB_DIR}/Eigen/src/SparseCore/SparseColEtree.h
${LIB_DIR}/Eigen/src/SparseCore/SparseUtil.h
${LIB_DIR}/Eigen/src/SparseCore/SparseView.h
${LIB_DIR}/Eigen/src/SparseCore/SparseMatrix.h
${LIB_DIR}/Eigen/src/SparseCore/SparseDenseProduct.h
${LIB_DIR}/Eigen/src/SparseCore/SparseSolverBase.h
${LIB_DIR}/Eigen/src/SparseCore/SparseFuzzy.h
${LIB_DIR}/Eigen/src/SparseCore/SparseSparseProductWithPruning.h
${LIB_DIR}/Eigen/src/SparseCore/SparseMatrixBase.h
${LIB_DIR}/Eigen/src/SparseCore/SparseDiagonalProduct.h
${LIB_DIR}/Eigen/src/SparseCore/SparseTriangularView.h
${LIB_DIR}/Eigen/src/SparseCore/SparseRedux.h
${LIB_DIR}/Eigen/src/SparseCore/SparseAssign.h
${LIB_DIR}/Eigen/src/SparseCore/SparseBlock.h
${LIB_DIR}/Eigen/src/SparseCore/TriangularSolver.h
${LIB_DIR}/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h
${LIB_DIR}/Eigen/src/SparseCore/SparsePermutation.h
${LIB_DIR}/Eigen/src/SparseCore/SparseTranspose.h
${LIB_DIR}/Eigen/src/SparseCore/SparseSelfAdjointView.h
${LIB_DIR}/Eigen/src/SparseCore/AmbiVector.h
${LIB_DIR}/Eigen/src/SparseCore/SparseDot.h
${LIB_DIR}/Eigen/src/SparseCore/MappedSparseMatrix.h
${LIB_DIR}/Eigen/src/SparseCore/SparseMap.h
${LIB_DIR}/Eigen/src/SparseCore/SparseProduct.h
${LIB_DIR}/Eigen/src/SparseCore/CompressedStorage.h
${LIB_DIR}/Eigen/src/SparseCore/SparseCwiseBinaryOp.h
${LIB_DIR}/Eigen/src/SparseCore/SparseRef.h
${LIB_DIR}/Eigen/src/plugins/IndexedViewMethods.h
${LIB_DIR}/Eigen/src/plugins/CommonCwiseBinaryOps.h
${LIB_DIR}/Eigen/src/plugins/ArrayCwiseUnaryOps.h
${LIB_DIR}/Eigen/src/plugins/BlockMethods.h
${LIB_DIR}/Eigen/src/plugins/ArrayCwiseBinaryOps.h
${LIB_DIR}/Eigen/src/plugins/MatrixCwiseBinaryOps.h
${LIB_DIR}/Eigen/src/plugins/MatrixCwiseUnaryOps.h
${LIB_DIR}/Eigen/src/plugins/CommonCwiseUnaryOps.h
${LIB_DIR}/Eigen/src/Cholesky/LLT_LAPACKE.h
${LIB_DIR}/Eigen/src/Cholesky/LLT.h
${LIB_DIR}/Eigen/src/Cholesky/LDLT.h
${LIB_DIR}/Eigen/src/OrderingMethods/Eigen_Colamd.h
${LIB_DIR}/Eigen/src/OrderingMethods/Ordering.h
${LIB_DIR}/Eigen/src/OrderingMethods/Amd.h
${LIB_DIR}/Eigen/src/Householder/BlockHouseholder.h
${LIB_DIR}/Eigen/src/Householder/HouseholderSequence.h
${LIB_DIR}/Eigen/src/Householder/Householder.h
${LIB_DIR}/Eigen/src/KLUSupport/KLUSupport.h
${LIB_DIR}/Eigen/src/CholmodSupport/CholmodSupport.h
${LIB_DIR}/Eigen/src/PaStiXSupport/PaStiXSupport.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h
${LIB_DIR}/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h)

set(EIGEN_DIRS
${LIB_DIR}/Eigen
${LIB_DIR}/Eigen/src
${LIB_DIR}/Eigen/src/SVD
${LIB_DIR}/Eigen/src/Jacobi
${LIB_DIR}/Eigen/src/Eigenvalues
${LIB_DIR}/Eigen/src/UmfPackSupport
${LIB_DIR}/Eigen/src/QR
${LIB_DIR}/Eigen/src/misc
${LIB_DIR}/Eigen/src/LU
${LIB_DIR}/Eigen/src/LU/arch
${LIB_DIR}/Eigen/src/SuperLUSupport
${LIB_DIR}/Eigen/src/Geometry
${LIB_DIR}/Eigen/src/Geometry/arch
${LIB_DIR}/Eigen/src/PardisoSupport
${LIB_DIR}/Eigen/src/SparseQR
${LIB_DIR}/Eigen/src/Core
${LIB_DIR}/Eigen/src/Core/products
${LIB_DIR}/Eigen/src/Core/arch
${LIB_DIR}/Eigen/src/Core/arch/AVX512
${LIB_DIR}/Eigen/src/Core/arch/AVX
${LIB_DIR}/Eigen/src/Core/arch/NEON
${LIB_DIR}/Eigen/src/Core/arch/CUDA
${LIB_DIR}/Eigen/src/Core/arch/Default
${LIB_DIR}/Eigen/src/Core/arch/AltiVec
${LIB_DIR}/Eigen/src/Core/arch/ZVector
${LIB_DIR}/Eigen/src/Core/arch/SSE
${LIB_DIR}/Eigen/src/Core/util
${LIB_DIR}/Eigen/src/Core/functors
${LIB_DIR}/Eigen/src/SparseLU
${LIB_DIR}/Eigen/src/SPQRSupport
${LIB_DIR}/Eigen/src/StlSupport
${LIB_DIR}/Eigen/src/MetisSupport
${LIB_DIR}/Eigen/src/SparseCholesky
${LIB_DIR}/Eigen/src/SparseCore
${LIB_DIR}/Eigen/src/plugins
${LIB_DIR}/Eigen/src/Cholesky
${LIB_DIR}/Eigen/src/OrderingMethods
${LIB_DIR}/Eigen/src/Householder
${LIB_DIR}/Eigen/src/KLUSupport
${LIB_DIR}/Eigen/src/CholmodSupport
${LIB_DIR}/Eigen/src/PaStiXSupport
${LIB_DIR}/Eigen/src/IterativeLinearSolvers)
