set(MBED_DIR ${LIB_DIR}/mbed-os)

set(MBED_SRC
    ${MBED_DIR}/drivers/AnalogIn.cpp
    ${MBED_DIR}/drivers/BusIn.cpp
    ${MBED_DIR}/drivers/BusInOut.cpp
    ${MBED_DIR}/drivers/BusOut.cpp
    ${MBED_DIR}/drivers/CAN.cpp
    ${MBED_DIR}/drivers/Ethernet.cpp
    ${MBED_DIR}/drivers/FlashIAP.cpp
    ${MBED_DIR}/drivers/I2C.cpp
    ${MBED_DIR}/drivers/I2CSlave.cpp
    ${MBED_DIR}/drivers/InterruptIn.cpp
    ${MBED_DIR}/drivers/InterruptManager.cpp
    ${MBED_DIR}/drivers/RawSerial.cpp
    ${MBED_DIR}/drivers/SerialBase.cpp
    ${MBED_DIR}/drivers/Serial.cpp
    ${MBED_DIR}/drivers/SPI.cpp
    ${MBED_DIR}/drivers/SPISlave.cpp
    ${MBED_DIR}/drivers/Ticker.cpp
    ${MBED_DIR}/drivers/Timeout.cpp
    ${MBED_DIR}/drivers/Timer.cpp
    ${MBED_DIR}/drivers/TimerEvent.cpp
    ${MBED_DIR}/drivers/UARTSerial.cpp
    ${MBED_DIR}/events/equeue/equeue.c
    ${MBED_DIR}/events/equeue/equeue_mbed.cpp
    ${MBED_DIR}/events/equeue/equeue_posix.c
    ${MBED_DIR}/events/EventQueue.cpp
    ${MBED_DIR}/events/mbed_shared_queues.cpp
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/emac_lwip.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/emac_stack_lwip.cpp
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/EthernetInterface.cpp
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lpc17_emac.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lpc_phy_dp83848.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_api_lib.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_api_msg.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_err.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_netbuf.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_netdb.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_netifapi.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_sockets.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/api/lwip_tcpip.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_autoip.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_dhcp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_etharp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_icmp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_igmp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_ip4_addr.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_ip4.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv4/lwip_ip4_frag.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_dhcp6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ethip6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_icmp6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_inet6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ip6_addr.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ip6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_ip6_frag.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_mld6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/ipv6/lwip_nd6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_def.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_dns.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_inet_chksum.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_init.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_ip.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_mem.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_memp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_netif.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_pbuf.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_raw.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_stats.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_sys.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp_in.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_tcp_out.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_timeouts.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/core/lwip_udp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/lwip_ethernet.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/lwip_ethernetif.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/lwip_lowpan6.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_auth.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ccp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_chap-md5.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_chap_ms.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_chap-new.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_demand.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_eap.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ecp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_eui64.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_fsm.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ipcp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ipv6cp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_lcp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_magic.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_mppe.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_multilink.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppapi.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_ppp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppcrypt.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppoe.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppol2tp.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_pppos.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_upap.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_utils.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/lwip_vj.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_arc4.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_des.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_md4.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_md5.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/netif/ppp/polarssl/lwip_sha1.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip_stack.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_checksum.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_memcpy.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_random.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_tcp_isn.c
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp
    ${MBED_DIR}/features/filesystem/bd/ChainingBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/ExhaustibleBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/HeapBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/MBRBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/ObservingBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/ProfilingBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/ReadOnlyBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/bd/SlicingBlockDevice.cpp
    ${MBED_DIR}/features/filesystem/Dir.cpp
    ${MBED_DIR}/features/filesystem/fat/ChaN/ff.cpp
    ${MBED_DIR}/features/filesystem/fat/ChaN/ffunicode.cpp
    ${MBED_DIR}/features/filesystem/fat/FATFileSystem.cpp
    ${MBED_DIR}/features/filesystem/File.cpp
    ${MBED_DIR}/features/filesystem/FileSystem.cpp
    ${MBED_DIR}/features/filesystem/littlefs/LittleFileSystem.cpp
    ${MBED_DIR}/features/filesystem/littlefs/littlefs/lfs.c
    ${MBED_DIR}/features/filesystem/littlefs/littlefs/lfs_util.c
    ${MBED_DIR}/features/frameworks/greentea-client/source/greentea_metrics.cpp
    ${MBED_DIR}/features/frameworks/greentea-client/source/greentea_serial.cpp
    ${MBED_DIR}/features/frameworks/greentea-client/source/greentea_test_env.cpp
    ${MBED_DIR}/features/frameworks/unity/source/unity.c
    ${MBED_DIR}/features/frameworks/utest/mbed-utest-shim.cpp
    ${MBED_DIR}/features/frameworks/utest/source/unity_handler.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_case.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_default_handlers.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_greentea_handlers.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_harness.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_shim.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_stack_trace.cpp
    ${MBED_DIR}/features/frameworks/utest/source/utest_types.cpp
    ${MBED_DIR}/features/mbedtls/platform/src/mbed_trng.c
    ${MBED_DIR}/features/mbedtls/src/aes.c
    ${MBED_DIR}/features/mbedtls/src/aesni.c
    ${MBED_DIR}/features/mbedtls/src/arc4.c
    ${MBED_DIR}/features/mbedtls/src/asn1parse.c
    ${MBED_DIR}/features/mbedtls/src/asn1write.c
    ${MBED_DIR}/features/mbedtls/src/base64.c
    ${MBED_DIR}/features/mbedtls/src/bignum.c
    ${MBED_DIR}/features/mbedtls/src/blowfish.c
    ${MBED_DIR}/features/mbedtls/src/camellia.c
    ${MBED_DIR}/features/mbedtls/src/ccm.c
    ${MBED_DIR}/features/mbedtls/src/certs.c
    ${MBED_DIR}/features/mbedtls/src/cipher.c
    ${MBED_DIR}/features/mbedtls/src/cipher_wrap.c
    ${MBED_DIR}/features/mbedtls/src/cmac.c
    ${MBED_DIR}/features/mbedtls/src/ctr_drbg.c
    ${MBED_DIR}/features/mbedtls/src/debug.c
    ${MBED_DIR}/features/mbedtls/src/des.c
    ${MBED_DIR}/features/mbedtls/src/dhm.c
    ${MBED_DIR}/features/mbedtls/src/ecdh.c
    ${MBED_DIR}/features/mbedtls/src/ecdsa.c
    ${MBED_DIR}/features/mbedtls/src/ecjpake.c
    ${MBED_DIR}/features/mbedtls/src/ecp.c
    ${MBED_DIR}/features/mbedtls/src/ecp_curves.c
    ${MBED_DIR}/features/mbedtls/src/entropy.c
    ${MBED_DIR}/features/mbedtls/src/entropy_poll.c
    ${MBED_DIR}/features/mbedtls/src/error.c
    ${MBED_DIR}/features/mbedtls/src/gcm.c
    ${MBED_DIR}/features/mbedtls/src/havege.c
    ${MBED_DIR}/features/mbedtls/src/hmac_drbg.c
    ${MBED_DIR}/features/mbedtls/src/md2.c
    ${MBED_DIR}/features/mbedtls/src/md4.c
    ${MBED_DIR}/features/mbedtls/src/md5.c
    ${MBED_DIR}/features/mbedtls/src/md.c
    ${MBED_DIR}/features/mbedtls/src/md_wrap.c
    ${MBED_DIR}/features/mbedtls/src/memory_buffer_alloc.c
    ${MBED_DIR}/features/mbedtls/src/net_sockets.c
    ${MBED_DIR}/features/mbedtls/src/oid.c
    ${MBED_DIR}/features/mbedtls/src/padlock.c
    ${MBED_DIR}/features/mbedtls/src/pem.c
    ${MBED_DIR}/features/mbedtls/src/pk.c
    ${MBED_DIR}/features/mbedtls/src/pkcs11.c
    ${MBED_DIR}/features/mbedtls/src/pkcs12.c
    ${MBED_DIR}/features/mbedtls/src/pkcs5.c
    ${MBED_DIR}/features/mbedtls/src/pkparse.c
    ${MBED_DIR}/features/mbedtls/src/pk_wrap.c
    ${MBED_DIR}/features/mbedtls/src/pkwrite.c
    ${MBED_DIR}/features/mbedtls/src/platform.c
    ${MBED_DIR}/features/mbedtls/src/ripemd160.c
    ${MBED_DIR}/features/mbedtls/src/rsa.c
    ${MBED_DIR}/features/mbedtls/src/sha1.c
    ${MBED_DIR}/features/mbedtls/src/sha256.c
    ${MBED_DIR}/features/mbedtls/src/sha512.c
    ${MBED_DIR}/features/mbedtls/src/ssl_cache.c
    ${MBED_DIR}/features/mbedtls/src/ssl_ciphersuites.c
    ${MBED_DIR}/features/mbedtls/src/ssl_cli.c
    ${MBED_DIR}/features/mbedtls/src/ssl_cookie.c
    ${MBED_DIR}/features/mbedtls/src/ssl_srv.c
    ${MBED_DIR}/features/mbedtls/src/ssl_ticket.c
    ${MBED_DIR}/features/mbedtls/src/ssl_tls.c
    ${MBED_DIR}/features/mbedtls/src/threading.c
    ${MBED_DIR}/features/mbedtls/src/timing.c
    ${MBED_DIR}/features/mbedtls/src/version.c
    ${MBED_DIR}/features/mbedtls/src/version_features.c
    ${MBED_DIR}/features/mbedtls/src/x509.c
    ${MBED_DIR}/features/mbedtls/src/x509_create.c
    ${MBED_DIR}/features/mbedtls/src/x509_crl.c
    ${MBED_DIR}/features/mbedtls/src/x509_crt.c
    ${MBED_DIR}/features/mbedtls/src/x509_csr.c
    ${MBED_DIR}/features/mbedtls/src/x509write_crt.c
    ${MBED_DIR}/features/mbedtls/src/x509write_csr.c
    ${MBED_DIR}/features/mbedtls/src/xtea.c
    ${MBED_DIR}/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.cpp
    ${MBED_DIR}/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
    ${MBED_DIR}/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.cpp
    ${MBED_DIR}/features/netsocket/NetworkInterface.cpp
    ${MBED_DIR}/features/netsocket/NetworkStack.cpp
    ${MBED_DIR}/features/netsocket/nsapi_dns.cpp
    ${MBED_DIR}/features/netsocket/SocketAddress.cpp
    ${MBED_DIR}/features/netsocket/Socket.cpp
    ${MBED_DIR}/features/netsocket/TCPServer.cpp
    ${MBED_DIR}/features/netsocket/TCPSocket.cpp
    ${MBED_DIR}/features/netsocket/UDPSocket.cpp
    ${MBED_DIR}/features/netsocket/WiFiAccessPoint.cpp
    ${MBED_DIR}/hal/mbed_flash_api.c
    ${MBED_DIR}/hal/mbed_gpio.c
    ${MBED_DIR}/hal/mbed_lp_ticker_api.c
    ${MBED_DIR}/hal/mbed_pinmap_common.c
    ${MBED_DIR}/hal/mbed_sleep_manager.c
    ${MBED_DIR}/hal/mbed_ticker_api.c
    ${MBED_DIR}/hal/mbed_us_ticker_api.c
    ${MBED_DIR}/platform/ATCmdParser.cpp
    ${MBED_DIR}/platform/CallChain.cpp
    ${MBED_DIR}/platform/FileBase.cpp
    ${MBED_DIR}/platform/FileHandle.cpp
    ${MBED_DIR}/platform/FilePath.cpp
    ${MBED_DIR}/platform/FileSystemHandle.cpp
    ${MBED_DIR}/platform/LocalFileSystem.cpp
    ${MBED_DIR}/platform/mbed_alloc_wrappers.cpp
    ${MBED_DIR}/platform/mbed_application.c
    ${MBED_DIR}/platform/mbed_assert.c
    ${MBED_DIR}/platform/mbed_board.c
    ${MBED_DIR}/platform/mbed_critical.c
    ${MBED_DIR}/platform/mbed_error.c
    ${MBED_DIR}/platform/mbed_interface.c
    ${MBED_DIR}/platform/mbed_mem_trace.cpp
    ${MBED_DIR}/platform/mbed_mktime.c
    ${MBED_DIR}/platform/mbed_poll.cpp
    ${MBED_DIR}/platform/mbed_retarget.cpp
    ${MBED_DIR}/platform/mbed_rtc_time.cpp
    ${MBED_DIR}/platform/mbed_sdk_boot.c
    ${MBED_DIR}/platform/mbed_semihost_api.c
    ${MBED_DIR}/platform/mbed_stats.c
    ${MBED_DIR}/platform/mbed_wait_api_no_rtos.c
    ${MBED_DIR}/platform/mbed_wait_api_rtos.cpp
    ${MBED_DIR}/platform/Stream.cpp
    ${MBED_DIR}/rtos/ConditionVariable.cpp
    ${MBED_DIR}/rtos/EventFlags.cpp
    ${MBED_DIR}/rtos/Kernel.cpp
    ${MBED_DIR}/rtos/Mutex.cpp
    ${MBED_DIR}/rtos/RtosTimer.cpp
    ${MBED_DIR}/rtos/Semaphore.cpp
    ${MBED_DIR}/rtos/TARGET_CORTEX/mbed_boot.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/mbed_rtx_handlers.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx4/cmsis_os1.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M3/irq_cm3.S
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/Source/os_systick.c
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.c
    ${MBED_DIR}/rtos/Thread.cpp
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/analogin_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/analogout_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/can_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/CRP.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/startup_LPC17xx.S
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/flash_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/system_LPC17xx.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/ethernet_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/gpio_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/gpio_irq_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/i2c_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/pinmap.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/port_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/pwmout_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/rtc_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/serial_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/sleep.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/spi_api.c
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/us_ticker.c

    ${MBED_DIR}/platform/platform.h
    ${MBED_DIR}/platform/mbed_preprocessor.h
    ${MBED_DIR}/platform/FileBase.h
    ${MBED_DIR}/platform/FileSystemHandle.h
    ${MBED_DIR}/platform/sleep.h
    ${MBED_DIR}/platform/FilePath.h
    ${MBED_DIR}/platform/mbed_critical.h
    ${MBED_DIR}/platform/critical.h
    ${MBED_DIR}/platform/mbed_poll.h
    ${MBED_DIR}/platform/PlatformMutex.h
    ${MBED_DIR}/platform/mbed_interface.h
    ${MBED_DIR}/platform/mbed_wait_api.h
    ${MBED_DIR}/platform/mbed_application.h
    ${MBED_DIR}/platform/semihost_api.h
    ${MBED_DIR}/platform/mbed_sleep.h
    ${MBED_DIR}/platform/CriticalSectionLock.h
    ${MBED_DIR}/platform/FileSystemLike.h
    ${MBED_DIR}/platform/mbed_debug.h
    ${MBED_DIR}/platform/LocalFileSystem.h
    ${MBED_DIR}/platform/CallChain.h
    ${MBED_DIR}/platform/mbed_assert.h
    ${MBED_DIR}/platform/DeepSleepLock.h
    ${MBED_DIR}/platform/mbed_toolchain.h
    ${MBED_DIR}/platform/NonCopyable.h
    ${MBED_DIR}/platform/FileLike.h
    ${MBED_DIR}/platform/ATCmdParser.h
    ${MBED_DIR}/platform/toolchain.h
    ${MBED_DIR}/platform/wait_api.h
    ${MBED_DIR}/platform/Callback.h
    ${MBED_DIR}/platform/CThunk.h
    ${MBED_DIR}/platform/FunctionPointer.h
    ${MBED_DIR}/platform/Transaction.h
    ${MBED_DIR}/platform/DirHandle.h
    ${MBED_DIR}/platform/mbed_rtc_time.h
    ${MBED_DIR}/platform/FileHandle.h
    ${MBED_DIR}/platform/mbed_retarget.h
    ${MBED_DIR}/platform/Stream.h
    ${MBED_DIR}/platform/mbed_mem_trace.h
    ${MBED_DIR}/platform/SingletonPtr.h
    ${MBED_DIR}/platform/mbed_mktime.h
    ${MBED_DIR}/platform/rtc_time.h
    ${MBED_DIR}/platform/mbed_error.h
    ${MBED_DIR}/platform/mbed_semihost_api.h
    ${MBED_DIR}/platform/CircularBuffer.h
    ${MBED_DIR}/platform/mbed_stats.h
    ${MBED_DIR}/mbed.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/objects.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/gpio_object.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/cmsis_nvic.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/cmsis.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/LPC17xx.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/device/system_LPC17xx.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/reserved_pins.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/device.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/PinNames.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/PortNames.h
    ${MBED_DIR}/targets/TARGET_NXP/TARGET_LPC176X/PeripheralNames.h
    ${MBED_DIR}/targets/TARGET_NXP/mbed_rtx.h
    ${MBED_DIR}/events/Event.h
    ${MBED_DIR}/events/equeue/equeue_platform.h
    ${MBED_DIR}/events/equeue/equeue.h
    ${MBED_DIR}/events/mbed_events.h
    ${MBED_DIR}/events/mbed_shared_queues.h
    ${MBED_DIR}/events/EventQueue.h
    ${MBED_DIR}/rtos/RtosTimer.h
    ${MBED_DIR}/rtos/Mutex.h
    ${MBED_DIR}/rtos/EventFlags.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/mbed_rtos_storage.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/mbed_rtos1_types.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx4/cmsis_os.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/mbed_rtx_conf.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/Include/cmsis_os2.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/Include/os_tick.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Include/rtx_evr.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Include/rtx_os.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_c.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_cm.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_ca.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.h
    ${MBED_DIR}/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.h
    ${MBED_DIR}/rtos/ConditionVariable.h
    ${MBED_DIR}/rtos/Thread.h
    ${MBED_DIR}/rtos/MemoryPool.h
    ${MBED_DIR}/rtos/Queue.h
    ${MBED_DIR}/rtos/rtos.h
    ${MBED_DIR}/rtos/Semaphore.h
    ${MBED_DIR}/rtos/rtos_idle.h
    ${MBED_DIR}/rtos/Mail.h
    ${MBED_DIR}/rtos/Kernel.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lpc_phy.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lpc_emac_config.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lpc17xx_emac.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lwipopts_conf.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip_stack.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/EthernetInterface.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/ppp_lwip.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwipopts.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/autoip.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/icmp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/dhcp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/timeouts.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/sys.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netdb.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ethip6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/snmp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netbuf.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/nd6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/inet.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/raw.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/tcp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/init.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/mld6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/lwip_errno.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/dns.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip4_addr.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/arch.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip4.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip4_frag.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/api.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv/memp_priv.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv/tcp_priv.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv/tcpip_priv.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv/memp_std.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv/api_msg.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/priv/nd6_priv.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip6_addr.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/opt.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/stats.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/sio.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/def.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip_addr.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/mem.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/pbuf.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/err.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/inet_chksum.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/memp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/icmp6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/tcpip.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/igmp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netif.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netifapi.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip6_frag.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/dhcp6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/sockets.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/udp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/debug.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/ip.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/autoip.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/icmp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/dhcp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/nd6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/tcp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/mld6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/dns.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/ip4.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/lwip_ethernet.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/icmp6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/igmp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/udp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/ip6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/prot/etharp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/ip6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/etharp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/lowpan6_opts.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/lwip_ethernet.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/lowpan6.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/pppapi.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/pppos.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/fsm.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ipv6cp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ecp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ccp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/eui64.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ipcp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/eap.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/chap-md5.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/chap-new.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/pppcrypt.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl/sha1.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl/md4.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl/arc4.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl/md5.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/polarssl/des.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/upap.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/pppoe.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/vj.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/chap_ms.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/mppe.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ppp_impl.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/lcp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/magic.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/pppdebug.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ppp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/pppol2tp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/ppp/ppp_opts.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/etharp.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip/src/include/netif/slipif.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/eth_arch.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_random.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/perf.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/sys_arch.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/cc.h
    ${MBED_DIR}/features/FEATURE_LWIP/lwip-interface/lwip-sys/lwip_tcp_isn.h
    ${MBED_DIR}/features/mbedtls/platform/inc/platform_mbed.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/pkcs12.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/platform.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ecjpake.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/x509_crt.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/base64.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/cmac.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/sha1.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/camellia.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ssl_ciphersuites.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/pkcs5.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/sha512.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/cipher_internal.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/md4.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/xtea.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ssl_ticket.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ecp.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/x509_csr.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/cipher.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/entropy_poll.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ctr_drbg.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/x509.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ecp_internal.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/md2.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ssl.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/sha256.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/timing.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/padlock.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/threading.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/x509_crl.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ecdh.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/bignum.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ripemd160.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/arc4.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/blowfish.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/certs.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/error.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ssl_internal.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/config-no-entropy.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/hmac_drbg.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/asn1.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/memory_buffer_alloc.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/check_config.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/md.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/platform_time.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/pk.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/md_internal.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ccm.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/rsa.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/dhm.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/md5.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/net.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ecdsa.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/version.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/gcm.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/net_sockets.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/bn_mul.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/aesni.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/asn1write.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/des.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/pkcs11.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/pk_internal.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/compat-1.3.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/debug.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/oid.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/havege.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/config.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ssl_cache.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/entropy.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/pem.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/aes.h
    ${MBED_DIR}/features/mbedtls/inc/mbedtls/ssl_cookie.h
    ${MBED_DIR}/features/filesystem/FileSystem.h
    ${MBED_DIR}/features/filesystem/mbed_filesystem.h
    ${MBED_DIR}/features/filesystem/File.h
    ${MBED_DIR}/features/filesystem/littlefs/LittleFileSystem.h
    ${MBED_DIR}/features/filesystem/littlefs/littlefs/lfs_util.h
    ${MBED_DIR}/features/filesystem/littlefs/littlefs/lfs.h
    ${MBED_DIR}/features/filesystem/Dir.h
    ${MBED_DIR}/features/filesystem/bd/MBRBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/BlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/SlicingBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/ReadOnlyBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/ExhaustibleBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/ProfilingBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/ChainingBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/ObservingBlockDevice.h
    ${MBED_DIR}/features/filesystem/bd/HeapBlockDevice.h
    ${MBED_DIR}/features/filesystem/fat/FATFileSystem.h
    ${MBED_DIR}/features/filesystem/fat/ChaN/integer.h
    ${MBED_DIR}/features/filesystem/fat/ChaN/ff.h
    ${MBED_DIR}/features/filesystem/fat/ChaN/ffconf.h
    ${MBED_DIR}/features/filesystem/fat/ChaN/diskio.h
    ${MBED_DIR}/features/netsocket/nsapi_dns.h
    ${MBED_DIR}/features/netsocket/WiFiAccessPoint.h
    ${MBED_DIR}/features/netsocket/cellular/onboard_modem_api.h
    ${MBED_DIR}/features/netsocket/cellular/utils/APN_db.h
    ${MBED_DIR}/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.h
    ${MBED_DIR}/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.h
    ${MBED_DIR}/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.h
    ${MBED_DIR}/features/netsocket/TCPSocket.h
    ${MBED_DIR}/features/netsocket/nsapi.h
    ${MBED_DIR}/features/netsocket/NetworkStack.h
    ${MBED_DIR}/features/netsocket/EthInterface.h
    ${MBED_DIR}/features/netsocket/TCPServer.h
    ${MBED_DIR}/features/netsocket/SocketAddress.h
    ${MBED_DIR}/features/netsocket/MeshInterface.h
    ${MBED_DIR}/features/netsocket/nsapi_types.h
    ${MBED_DIR}/features/netsocket/WiFiInterface.h
    ${MBED_DIR}/features/netsocket/nsapi_ppp.h
    ${MBED_DIR}/features/netsocket/NetworkInterface.h
    ${MBED_DIR}/features/netsocket/Socket.h
    ${MBED_DIR}/features/netsocket/UDPSocket.h
    ${MBED_DIR}/features/netsocket/CellularInterface.h
    ${MBED_DIR}/features/netsocket/CellularBase.h
    ${MBED_DIR}/features/netsocket/emac_stack_mem.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_types.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_case.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_specification.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_scheduler.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_serial.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_shim.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_default_handlers.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_stack_trace.h
    ${MBED_DIR}/features/frameworks/utest/utest/unity_handler.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest.h
    ${MBED_DIR}/features/frameworks/utest/utest/utest_harness.h
    ${MBED_DIR}/features/frameworks/greentea-client/greentea-client/greentea_serial.h
    ${MBED_DIR}/features/frameworks/greentea-client/greentea-client/greentea_metrics.h
    ${MBED_DIR}/features/frameworks/greentea-client/greentea-client/test_env.h
    ${MBED_DIR}/features/frameworks/unity/unity/unity.h
    ${MBED_DIR}/features/frameworks/unity/unity/unity_internals.h
    ${MBED_DIR}/features/frameworks/unity/unity/unity_config.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_sc300.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm4.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/cmsis_armclang.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm0plus.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/mpu_armv7.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cmSecureAccess.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm23.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/arm_math.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_armv8mml.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm33.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm7.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/cmsis_armcc.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/tz_context.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm0.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/cmsis_compiler.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_cm3.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_sc000.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/cmsis_version.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/cmsis_gcc.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/cmsis_iccarm.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/core_armv8mbl.h
    ${MBED_DIR}/cmsis/TARGET_CORTEX_M/mpu_armv8.h
    ${MBED_DIR}/hal/lp_ticker_api.h
    ${MBED_DIR}/hal/ticker_api.h
    ${MBED_DIR}/hal/flash_api.h
    ${MBED_DIR}/hal/analogin_api.h
    ${MBED_DIR}/hal/gpio_irq_api.h
    ${MBED_DIR}/hal/dma_api.h
    ${MBED_DIR}/hal/pwmout_api.h
    ${MBED_DIR}/hal/us_ticker_api.h
    ${MBED_DIR}/hal/gpio_api.h
    ${MBED_DIR}/hal/can_helper.h
    ${MBED_DIR}/hal/trng_api.h
    ${MBED_DIR}/hal/can_api.h
    ${MBED_DIR}/hal/emac_api.h
    ${MBED_DIR}/hal/serial_api.h
    ${MBED_DIR}/hal/buffer.h
    ${MBED_DIR}/hal/i2c_api.h
    ${MBED_DIR}/hal/sleep_api.h
    ${MBED_DIR}/hal/storage_abstraction/Driver_Storage.h
    ${MBED_DIR}/hal/storage_abstraction/Driver_Common.h
    ${MBED_DIR}/hal/ethernet_api.h
    ${MBED_DIR}/hal/rtc_api.h
    ${MBED_DIR}/hal/analogout_api.h
    ${MBED_DIR}/hal/spi_api.h
    ${MBED_DIR}/hal/port_api.h
    ${MBED_DIR}/hal/pinmap.h
    ${MBED_DIR}/drivers/DigitalIn.h
    ${MBED_DIR}/drivers/PortInOut.h
    ${MBED_DIR}/drivers/SerialBase.h
    ${MBED_DIR}/drivers/Timer.h
    ${MBED_DIR}/drivers/LowPowerTimeout.h
    ${MBED_DIR}/drivers/BusOut.h
    ${MBED_DIR}/drivers/LowPowerTimer.h
    ${MBED_DIR}/drivers/AnalogIn.h
    ${MBED_DIR}/drivers/DigitalOut.h
    ${MBED_DIR}/drivers/I2CSlave.h
    ${MBED_DIR}/drivers/SPISlave.h
    ${MBED_DIR}/drivers/RawSerial.h
    ${MBED_DIR}/drivers/LowPowerTicker.h
    ${MBED_DIR}/drivers/CAN.h
    ${MBED_DIR}/drivers/PortIn.h
    ${MBED_DIR}/drivers/PortOut.h
    ${MBED_DIR}/drivers/AnalogOut.h
    ${MBED_DIR}/drivers/UARTSerial.h
    ${MBED_DIR}/drivers/Ethernet.h
    ${MBED_DIR}/drivers/SPI.h
    ${MBED_DIR}/drivers/InterruptManager.h
    ${MBED_DIR}/drivers/InterruptIn.h
    ${MBED_DIR}/drivers/TimerEvent.h
    ${MBED_DIR}/drivers/BusInOut.h
    ${MBED_DIR}/drivers/PwmOut.h
    ${MBED_DIR}/drivers/DigitalInOut.h
    ${MBED_DIR}/drivers/Serial.h
    ${MBED_DIR}/drivers/FlashIAP.h
    ${MBED_DIR}/drivers/I2C.h
    ${MBED_DIR}/drivers/Ticker.h
    ${MBED_DIR}/drivers/Timeout.h
    ${MBED_DIR}/drivers/BusIn.h)
