set(MBED_DEVICE_FEATURES
	"I2CSLAVE" "RTC" "CAN" "ANALOGOUT" "PWMOUT" "INTERRUPTIN" "I2C" "PORTOUT" "STDIO_MESSAGES" "PORTINOUT"
	"SERIAL_FC" "PORTIN" "SLEEP" "SPI" "ETHERNET" "SPISLAVE" "ANALOGIN" "SERIAL" "FLASH" "SEMIHOST"
	"DEBUG_AWARENESS" "LOCALFILESYSTEM")

foreach(feature ${MBED_DEVICE_FEATURES})
	set(MBED_DEFINES "${MBED_DEFINES} -DDEVICE_${feature}=1")
endforeach()

set(MBED_PREPROCESSOR_OPTS
	"TARGET_LPC176X" "TARGET_CORTEX_M" "TARGET_LIKE_CORTEX_M3" "TARGET_LPCTarget" "TARGET_CORTEX" "TARGET_LIKE_MBED"
	"TARGET_RELEASE" "TARGET_NXP" "TARGET_LPC1768" "TARGET_M3" "TARGET_MBED_LPC1768" "TOOLCHAIN_GCC_ARM" "__CORTEX_M3"
	"__CMSIS_RTOS" "ARM_MATH_CM3" "MBED_BUILD_TIMESTAMP=1510862730.04" "DEVICE_ERROR_PATTERN=1" "FEATURE_LWIP=1"
	"__MBED__=1" "__MBED_CMSIS_RTOS_CM" "TOOLCHAIN_object" "TOOLCHAIN_GCC" "TARGET_UVISOR_UNSUPPORTED"
	"TRANSACTION_QUEUE_SIZE=2" "TRANSACTION_QUEUE_SIZE_SPI=2" "MBED_CONF_PLATFORM_STDIO_BAUD_RATE=9600"
	"MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE=9600" "MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT=1"
	"MBED_CONF_PLATFORM_STIO_CONVERT_NEWLINES=0")

foreach(opt ${MBED_PREPROCESSOR_OPTS})
	set(MBED_DEFINES "${MBED_DEFINES} -D${opt}")
endforeach()
